Repository GSG-G10/Jole-Library, pull requests merged in 2021-08, with the labels that each got.

#4 create the file structure
  .gitignore
  package-lock.json
  package.json
  public/css/404.css
  public/css/500.css
  public/css/addbook.css
  public/css/home.css
  public/css/search.css
  public/html/404.html
  public/html/500.html
  public/html/addbook.html
  public/html/search.html
  public/index.html
  public/js/dom.js
  public/js/fetch.js
  server/app.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/conection.js
  server/database/config/data.sql
  server/database/queries/index.js
  server/database/queries/postdata.js
  server/database/queries/searchdata.js
  server/index.js
  test/test.js
Labels: Awaiting Review

#6 create database
  server/database/config/data.sql
Labels: Awaiting Review

#8 07 connect database
  .eslintrc.json
  package-lock.json
  package.json
  server/database/config/conection.js
  server/database/config/data.sql
Labels: Awaiting Review

#10 create server
  server/app.js
  server/index.js
Labels: Awaiting Review

#12 create function to build database
  server/database/config/build.js
  server/database/config/conection.js
Labels: Awaiting Review

#14 handle search data
  package.json
  server/database/queries/searchdata.js
Labels: Awaiting Review

#16 15 add data
  server/app.js
  server/database/config/build.js
  server/database/config/data.sql
  server/database/queries/index.js
  server/database/queries/postdata.js
  server/database/queries/searchdata.js
Labels: Awaiting Review, Done

#18 17 handle search post
  server/app.js
  server/controllers/index.js
Labels: Awaiting Review

#22 20 add html
  public/html/addbook.html
Labels: Awaiting Review

#21 create search html
  public/html/search.html
Labels: Done

#24 23 fetch searched data
  public/js/dom.js
  public/js/fetch.js
  server/app.js
  server/controllers/index.js
Labels: Awaiting Review

#28 create functions to create the cards and to display data in them && r…
  public/js/dom.js
Labels: Awaiting Review

#31 30 all book
  public/html/addbook.html
  public/html/search.html
  public/js/dom.js
  public/js/fetchAll.js
  public/js/fetchSearched.js
  server/app.js
  server/controllers/index.js
  server/database/queries/getAllData.js
  server/database/queries/index.js
Labels: Awaiting Review

#33 handle 404 error 500 error
  server/app.js
  server/controllers/errors.js
Labels: Awaiting Review

#34 creat home page css
  public/css/home.css
  public/image/jole-library-logo.png
  public/image/showbook1.jpg
  public/image/showbook2.jpg
  public/image/showbook3.jpg
  public/image/showbook4.jpg
  public/image/showbook5.jpg
  public/index.html
Labels: Done

#38 styling form page
  public/css/addbook.css
  public/html/addbook.html
Labels: Awaiting Review

#37 create css for searh html
  public/css/search.css
  public/html/search.html
  public/image/jole.png
  public/index.html
Labels: Awaiting Review

#40 styling cards
  public/css/search.css
  public/index.html
  server/database/config/data.sql
Labels: Awaiting Review

#41 3 readme
  README.md
Labels: Awaiting Review

#43 create html and css for error pages
  public/css/404.css
  public/css/500.css
  public/html/404.html
  public/html/500.html
  public/image/f.jpg
  public/image/f1.jpg
  public/image/f2.png
Labels: Awaiting Review

#45 edit style index, search and form pages
  public/css/addbook.css
  public/css/home.css
  public/css/search.css
  public/html/addbook.html
  public/html/search.html
  public/index.html
Labels: Awaiting Review

#46 edite connection
  package.json
  server/database/config/conection.js
Labels: Awaiting Review

#47 Edit website
  public/css/search.css
  public/html/addbook.html
  public/html/search.html
  server/database/config/conection.js
  server/database/queries/postdata.js
Labels: In Progress
